//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.29 at 10:25:38 PM MESZ 
//

package org.revager.app.model.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * An attendee who can take part in a review.
 * 
 * 
 * <p>
 * Java class for attendeeType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="attendeeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contact" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="role" type="{http://www.informatik.uni-stuttgart.de/iste/se}roleType"/>
 *         &lt;element name="aspects" type="{http://www.informatik.uni-stuttgart.de/iste/se}aspectsIdType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "attendeeType", propOrder = { "id", "name", "contact", "role", "aspects" })
public class Attendee {

	@XmlElement(required = true)
	protected String id;
	@XmlElement(required = true)
	protected String name;
	@XmlElement(required = true)
	protected String contact;
	@XmlElement(required = true)
	protected Role role;
	protected AspectsIds aspects;

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		this.id = value;
	}

	public boolean isSetId() {
		return (this.id != null);
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	public boolean isSetName() {
		return (this.name != null);
	}

	/**
	 * Gets the value of the contact property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * Sets the value of the contact property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setContact(String value) {
		this.contact = value;
	}

	public boolean isSetContact() {
		return (this.contact != null);
	}

	/**
	 * Gets the value of the role property.
	 * 
	 * @return possible object is {@link Role }
	 * 
	 */
	public Role getRole() {
		return role;
	}

	/**
	 * Sets the value of the role property.
	 * 
	 * @param value
	 *            allowed object is {@link Role }
	 * 
	 */
	public void setRole(Role value) {
		this.role = value;
	}

	public boolean isSetRole() {
		return (this.role != null);
	}

	/**
	 * Gets the value of the aspects property.
	 * 
	 * @return possible object is {@link AspectsIds }
	 * 
	 */
	public AspectsIds getAspects() {
		return aspects;
	}

	/**
	 * Sets the value of the aspects property.
	 * 
	 * @param value
	 *            allowed object is {@link AspectsIds }
	 * 
	 */
	public void setAspects(AspectsIds value) {
		this.aspects = value;
	}

	public boolean isSetAspects() {
		return (this.aspects != null);
	}

}
