//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.29 at 10:25:38 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.informatik.uni-stuttgart.de/iste/se", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.revager.app.model.schema;
